### ISSUE TITLE
Obsolete function variable_global_exists

### ISSUE THREAD

**Issue by RaniSputnik** [gmlscripts/scripts#8]
This function is used in a few scripts. These are the current offenders;

```
Gameplay/Collisions/collision_triangle_init
Graphics/Drawing/draw_rectangle_dashed
Graphics/Drawing/draw_rectangle_dashed_color
```

These scripts should be modified to no longer store global data - if possible.

**Comment by xotmatrix** [comment]
Thanks. They'll still need globals but they will changed to require explicit initialization.

**Comment by gmlscripts** [comment]
Thanks. They'll still need globals but they will be changed to require explicit initialization.

**Comment by xotmatrix** [comment]
Hooray for static variables!
